// <auto-generated />
using LogicaAccesoDatos.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogicaAccesoDatos.Migrations
{
    [DbContext(typeof(ObligatorioContext))]
    [Migration("20220910193909_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LogicaNegocio.Entidades.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Pais", b =>
                {
                    b.OwnsOne("LogicaNegocio.VO.ISOAlfa3", "IsoAlfa3", b1 =>
                        {
                            b1.Property<int>("PaisId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .HasColumnName("ISOAlfa3")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PaisId");

                            b1.ToTable("Paises");

                            b1.WithOwner()
                                .HasForeignKey("PaisId");
                        });

                    b.OwnsOne("LogicaNegocio.VO.Nombre", "Nombre", b1 =>
                        {
                            b1.Property<int>("PaisId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .HasColumnName("Nombre")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PaisId");

                            b1.ToTable("Paises");

                            b1.WithOwner()
                                .HasForeignKey("PaisId");
                        });

                    b.OwnsOne("LogicaNegocio.VO.PBI", "PBI", b1 =>
                        {
                            b1.Property<int>("PaisId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("Value")
                                .HasColumnName("PBI")
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("PaisId");

                            b1.ToTable("Paises");

                            b1.WithOwner()
                                .HasForeignKey("PaisId");
                        });

                    b.OwnsOne("LogicaNegocio.VO.Poblacion", "Poblacion", b1 =>
                        {
                            b1.Property<int>("PaisId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Value")
                                .HasColumnName("Poblacion")
                                .HasColumnType("int");

                            b1.HasKey("PaisId");

                            b1.ToTable("Paises");

                            b1.WithOwner()
                                .HasForeignKey("PaisId");
                        });

                    b.OwnsOne("LogicaNegocio.VO.Region", "Region", b1 =>
                        {
                            b1.Property<int>("PaisId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .HasColumnName("Region")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PaisId");

                            b1.ToTable("Paises");

                            b1.WithOwner()
                                .HasForeignKey("PaisId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
